version: '3.7'

services:
    backend:
        build: C:\Users\Q\Desktop\tp01\BackendAPI\simple-api-student-main
        networks:
          - my-network
        depends_on:
          - database

    database:
        build: C:\Users\Q\Desktop\tp01\Database
        networks:
          - my-network

    httpd:
        build: C:\Users\Q\Desktop\tp01\httpServer
        ports:
          - 8082:80
        networks:
          - my-network
        depends_on:
          - backend

networks:
    my-network:
